### ISSUE TITLE
App failed to work

### ISSUE THREAD

**Issue by besiwims** [rochus222/medium-modal-service#5]
When I click Show Profile this is what is displayed, {"data":{"name":"John Doe","phone":"123456","email":"john.doe@example.com"}}

There is no modal window being displayed.

**Comment by rochus222** [comment]
@besiwims this is very simple prototype that shows, how the data flow for modal with Redux can be setup. I did not bother with styling, so it seems like no modal is shown. However the JSON you mentioned is shown in separate modal div that only needs some styling (position fixed, some padding and background). I tried to write as little code as possible so the vital part is clear in [the article](https://medium.com/better-programming/modals-in-reactjs-631d801e2723) that was written as description for this solution. Writing some styles should not be a problem to any FE developer and would just make less straight forward code.
